name = "cruzhacks2025-api"
main = "worker.js"
compatibility_date = "2023-11-16"
usage_model = "bundled"
account_id = "79a8e716508fd7a826373d2b04ae814d"

[vars]
GEMINI_API_KEY = "YOUR_API_KEY_HERE"
FRONTEND_URL = "https://cruzhacks2025.pages.dev"

# Uncomment these once you've created the resources in Cloudflare
# [durable_objects]
# bindings = [
#   { name = "CONNECTION_MANAGER", class_name = "ConnectionManager" }
# ]

# [[kv_namespaces]]
# binding = "AUTH_STORE"
# id = "your-kv-namespace-id"

# [[d1_databases]]
# binding = "DB"
# database_name = "cruzhacks2025"
# database_id = "your-d1-database-id" 